kit/kit/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'', include('reminder.urls', namespace='reminder')),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'redirect_field_name': 'reminder/index.html'}),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page' : '/'}),
	#why can't we add create_user view here? Why is there not one?
	
	
    # Examples:
    # url(r'^$', 'kit.views.home', name='home'),
    # url(r'^kit/', include('kit.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kit/reminder/urls.py
from django.conf.urls import patterns,  url



urlpatterns = patterns('reminder.views',
	url(r'^$', 'index', name='index'),
	url(r'^add_friend$', 'add_friend', name='add_friend'),
	url(r'^add_friend/add$', 'add_friend_add', name='add_friend_add'),
	url(r'^add_event$', 'add_event', name='add_event'),
	url(r'^add_event/add$', 'add_event_add', name='add_event_add'),
	url(r'^accounts/add$', 'add_user', name='add_user'),
	url(r'^accounts/add/add$', 'add_user_add', name='add_user_add'),
	
    # Examples:
    # url(r'^$', 'kit.views.home', name='home'),
    # url(r'^kit/', include('kit.foo.urls')),
)

kit/reminder/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	
	# associated with one user
    
	user = models.OneToOneField(User)
	
	def __unicode__(self):
		return self.user.first_name

#------------------------------------------

class FriendProfile(models.Model):

	friend = models.ForeignKey(User, related_name='owns')
	firstName = models.CharField(max_length=40)
	lastName = models.CharField(max_length=40)
	blurb = models.CharField(max_length=140, blank=True)
	storyNotes = models.TextField(blank=True)
	
	def __unicode__(self):
		return self.firstName
	
class Event(models.Model):

	owner = models.ForeignKey(User, related_name='asked')
	participants = models.ManyToManyField('FriendProfile')
	name = models.CharField(max_length=40)
	
	#Frequency Categories
	WEEKLY = 'WE'
	MONTHLY = 'MO'
	BIWEEKLY = 'BI'
	YEARLY = 'YE'
	FREQUENCY_CHOICES = (
		(WEEKLY, 'Weekly'),
		(MONTHLY, 'Monthly'),
		(BIWEEKLY, 'Every other week'),
		(YEARLY, 'Yearly'),
	)
	frequency = models.CharField(max_length=2, choices=FREQUENCY_CHOICES, default=MONTHLY)
	time = models.DateField()
	
	emailReminder = models.BooleanField()
	
	text = models.TextField(blank=True)
	
	def __unicode__(self):
		return self.name

kit/reminder/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from django.contrib.auth.models import User
from reminder.models import FriendProfile, Event

def base(request):
	user = request.user
	context = { }
	return render(request, 'base.html', context)

def index(request):
	user = request.user
	# get only the friends and events of the user
	if user.is_authenticated():
		friend_list = user.owns.all
		event_list = user.asked.all
	else:
		friend_list = []
		event_list = []

	context = { 'friend_list' : friend_list, 'event_list' : event_list }
	return render(request, 'reminder/index.html', context)
	
def add_friend(request):
	context = { }
	return render(request, 'reminder/add_friend.html', context)
	
def add_event(request):
	possible_freq = []
	for freq in Event.FREQUENCY_CHOICES:
		possible_freq.append(freq[1])
	context = { 'possible_freq' : possible_freq }
	return render(request, 'reminder/add_event.html', context)
	
def add_friend_add(request):
	friend = FriendProfile(friend=request.user, firstName=request.POST['first_name'], lastName=request.POST['last_name'])
	friend.save()
	return HttpResponseRedirect('/')
	
def add_event_add(request):
	event = Event(owner=request.user,  
	name=request.POST['name'], 
	frequency=request.POST['frequency'], 
	time=request.POST['time'], 
	emailReminder=request.POST['emailReminder'], 
	text=request.POST['text'])
	event.save()
	event.participants.add(FriendProfile.objects.all()[0])
	event.save()
	return HttpResponseRedirect('/')
	
def friend_profile(request):
	context = {}
	return render(request, 'reminder/friend_profile.html', context)
	
def add_user(request):
	context = { }
	return render(request, 'registration/add_user.html', context)
	
def add_user_add(request):
	newUser = User.objects.create_user(request.POST['uname'],request.POST['email'], request.POST['pwd'])
	newUser.last_name = request.POST['last_name']
	newUser.first_name = request.POST['first_name']
	
	newUser.save()
	
	#add to UserProfiles
	addUserProf = newUser
	addUserProf.save()
	
	return HttpResponseRedirect('/')

kit/reminder/templates/reminder/add_event.html
{% extends "base.html" %}

{% block title %}babble-add event{% endblock %}

{% block content %}
<div class="container">
	<div class='page-header'><h1><strong>add a reminder</strong><br> <small>keep in touch with your friends</small></h1></div>

<form class="form-horizontal" role="form" action="{% url 'reminder:add_event_add' %}" method="post">
	{% csrf_token %}
	
	<div class="form-group">
		<label for="name" class="col-lg-2 control-label">reminder name:</label>
		<div class="col-lg-6"><input class="form-control" id="name" name="name" type="text"/></div>
	</div>
		
	<br>
	
	<div class="form-group">
		<label for="frequency" class="col-lg-2 control-label">remind me </label>
		<div class="col-lg-6">
			<select class="form-control" id="frequency" name="frequency">
				{% for freq in possible_freq %}
				<option value="{{ freq }}">{{ freq }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<br/>
	<div class="form-group">
		<label for="time" class="col-lg-2 control-label">first reminder on:</label>
		<div class="col-lg-6"><input class="form-control" id="time" name="time" type="date"/></div>
	</div>
	<br/>
	<div class="form-group">
		<label for="emailReminder" class="col-lg-2 control-label">set an email reminder:</label>
		<div class="col-lg-6"><input class="form-control" id="emailReminder" name="emailReminder" type="checkbox"/></div>
	</div>
	<br/>
	<div class="form-group">
		<label for="text" class="col-lg-2 control-label">description:</label>
		<div class="col-lg-6"><input class="form-control" id="text" name="text" type="text"/></div>
	</div>
	<br/>
	<label class='control-label'><input type="submit" value="create reminder" class="btn btn-primary"/></label>
	<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

kit/reminder/templates/reminder/add_friend.html
{% extends "base.html" %}

{% block title %}Add a Friend!{% endblock %}

{% block content %}
<div class="container">
	<div class='page-header'><h1><strong>add a friend</strong><br> <small>keep in touch with your friends</small></h1></div>

<form class="form-horizontal" role="form" action="{% url 'reminder:add_friend_add' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
			<label for="first_name" class="col-lg-2 control-label">first name:</label>
			<div class="col-lg-6"><input class="form-control" id="first_name" name="first_name" type="text"/></div>
		</div>
	<br/>	  	
	<div class="form-group">
		<label for="last_name" class="col-lg-2 control-label">last name:</label>
		<div class="col-lg-6"><input class="form-control" id="last_name" name="last_name" type="text"/></div>
	</div>	
	<br/>
	<div class="form-group">
		<label for="relationship" class="col-lg-2 control-label">relationship:</label>
		<div class="col-lg-6"><input class="form-control" id="relationship" name="relationship" type="text"/></div>
	</div>	
	<br/>
	<label class='control-label'><input type="submit" value="add friend reminder" class="btn btn-primary"/></label>
	<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/ads.html
<div id="carbonads-container"><div class="carbonad"><div id="azcarbon"></div><script>var z = document.createElement("script"); z.async = true; z.src = "http://engine.carbonads.com/z/32341/azcarbon_2_1_0_HORIZ"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(z, s);</script></div></div>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/footer.html
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ page.base_url }}assets/js/jquery.js"></script>
<script src="{{ page.base_url }}dist/js/bootstrap.js"></script>

<script src="http://platform.twitter.com/widgets.js"></script>
<script src="{{ page.base_url }}assets/js/holder.js"></script>

<script src="{{ page.base_url }}assets/js/application.js"></script>

{% if page.slug == "customize" %}
<script src="{{ page.base_url }}assets/js/less.js"></script>
<script src="{{ page.base_url }}assets/js/jszip.js"></script>
<script src="{{ page.base_url }}assets/js/uglify.js"></script>
<script src="{{ page.base_url }}assets/js/filesaver.js"></script>
<script src="{{ page.base_url }}assets/js/raw-files.js"></script>
<script src="{{ page.base_url }}assets/js/customizer.js"></script>
{% endif %}

<!-- Analytics
================================================== -->
<script>
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '4f0dc9fef5a1f55508000013');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/header.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<title>
  {% if page.title == "Bootstrap" %}
    {{ page.title }}
  {% else if %}
    {{ page.title }} &middot; Bootstrap
  {% endif %}
</title>

<!-- Bootstrap core CSS -->
<link href="{{ page.base_url }}dist/css/bootstrap.css" rel="stylesheet">

<!-- Documentation extras -->
<link href="{{ page.base_url }}assets/css/docs.css" rel="stylesheet">
<link href="{{ page.base_url }}assets/css/pygments-manni.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="{{ page.base_url }}assets/js/html5shiv.js"></script>
  <script src="{{ page.base_url }}assets/js/respond.min.js"></script>
<![endif]-->

<!-- Favicons -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ page.base_url }}assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ page.base_url }}assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ page.base_url }}assets/ico/apple-touch-icon-72-precomposed.png">
                <link rel="apple-touch-icon-precomposed" href="{{ page.base_url }}assets/ico/apple-touch-icon-57-precomposed.png">
                               <link rel="shortcut icon" href="{{ page.base_url }}assets/ico/favicon.png">

<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-146052-10']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/nav-components.html
<li>
  <a href="#glyphicons">Glyphicons</a>
  <ul class="nav">
    <li><a href="#glyphicons-glyphs">Available glyphs</a></li>
    <li><a href="#glyphicons-how-to-use">How to use</a></li>
    <li><a href="#glyphicons-examples">Examples</a></li>
  </ul>
</li>
<li>
  <a href="#dropdowns">Dropdowns</a>
  <ul class="nav">
    <li><a href="#dropdowns-example">Example</a></li>
    <li><a href="#dropdowns-alignment">Alignment options</a></li>
    <li><a href="#dropdowns-headers">Headers</a></li>
    <li><a href="#dropdowns-disabled">Disabled menu items</a></li>
  </ul>
</li>
<li>
  <a href="#btn-groups">Button groups</a>
  <ul class="nav">
    <li><a href="#btn-groups-single">Basic example</a></li>
    <li><a href="#btn-groups-toolbar">Button toolbar</a></li>
    <li><a href="#btn-groups-sizing">Sizing</a></li>
    <li><a href="#btn-groups-nested">Nesting</a></li>
    <li><a href="#btn-groups-vertical">Vertical variation</a></li>
    <li><a href="#btn-groups-justified">Justified link variation</a></li>
  </ul>
</li>
<li>
  <a href="#btn-dropdowns">Button dropdowns</a>
  <ul class="nav">
    <li><a href="#btn-dropdowns-single">Single button dropdowns</a></li>
    <li><a href="#btn-dropdowns-split">Split button dropdowns</a></li>
    <li><a href="#btn-dropdowns-sizing">Sizing</a></li>
    <li><a href="#btn-dropdowns-dropup">Dropup variation</a></li>
  </ul>
</li>
<li>
  <a href="#input-groups">Input groups</a>
  <ul class="nav">
    <li><a href="#input-groups-basic">Basic example</a></li>
    <li><a href="#input-groups-sizing">Sizing</a></li>
    <li><a href="#input-groups-checkboxes-radios">Checkbox and radios addons</a></li>
    <li><a href="#input-groups-buttons">Button addons</a></li>
    <li><a href="#input-groups-buttons-dropdowns">Buttons with dropdowns</a></li>
    <li><a href="#input-groups-buttons-segmented">Segmented buttons</a></li>
  </ul>
</li>
<li>
  <a href="#nav">Navs</a>
  <ul class="nav">
    <li><a href="#nav-tabs">Tabs</a></li>
    <li><a href="#nav-pills">Pills</a></li>
    <li><a href="#nav-justified">Justified nav</a></li>
    <li><a href="#nav-disabled-links">Disabled links</a></li>
    <li><a href="#nav-alignment">Alignment options</a></li>
    <li><a href="#nav-dropdowns">Using dropdowns</a></li>
  </ul>
</li>
<li>
  <a href="#navbar">Navbar</a>
  <ul class="nav">
    <li><a href="#navbar-default">Default navbar</a></li>
    <li><a href="#navbar-buttons">Buttons</a></li>
    <li><a href="#navbar-text">Text</a></li>
    <li><a href="#navbar-links">Non-nav links</a></li>
    <li><a href="#navbar-component-alignment">Component alignment</a></li>
    <li><a href="#navbar-fixed-top">Fixed to top</a></li>
    <li><a href="#navbar-fixed-bottom">Fixed to bottom</a></li>
    <li><a href="#navbar-static-top">Static top</a></li>
    <li><a href="#navbar-inverted">Inverted navbar</a></li>
  </ul>
</li>
<li><a href="#breadcrumbs">Breadcrumbs</a></li>
<li>
  <a href="#pagination">Pagination</a>
  <ul class="nav">
    <li><a href="#pagination-default">Default pagination</a></li>
    <li><a href="#pagination-pager">Pager</a></li>
  </ul>
</li>
<li><a href="#labels">Labels</a></li>
<li><a href="#badges">Badges</a></li>
<li><a href="#jumbotron">Jumbotron</a></li>
<li><a href="#page-header">Page header</a></li>
<li>
  <a href="#thumbnails">Thumbnails</a>
  <ul class="nav">
    <li><a href="#thumbnails-default">Default example</a></li>
    <li><a href="#thumbnails-custom-content">Custom content</a></li>
  </ul>
</li>
<li>
  <a href="#alerts">Alerts</a>
  <ul class="nav">
    <li><a href="#alerts-examples">Examples</a></li>
    <li><a href="#alerts-dismissable">Dismissable alerts</a></li>
    <li><a href="#alerts-links">Links in alerts</a></li>
  </ul>
</li>
<li>
  <a href="#progress">Progress bars</a>
  <ul class="nav">
    <li><a href="#progress-basic">Basic example</a></li>
    <li><a href="#progress-alternatives">Contextual alternatives</a></li>
    <li><a href="#progress-striped">Striped</a></li>
    <li><a href="#progress-animated">Animated</a></li>
    <li><a href="#progress-stacked">Stacked</a></li>
  </ul>
</li>
<li>
  <a href="#media">Media object</a>
  <ul class="nav">
    <li><a href="#media-default">Default media</a></li>
    <li><a href="#media-list">Media list</a></li>
  </ul>
</li>
<li>
  <a href="#list-group">List group</a>
  <ul class="nav">
    <li><a href="#list-group-basic">Basic example</a></li>
    <li><a href="#list-group-badges">Badges</a></li>
    <li><a href="#list-group-linked">Linked items</a></li>
    <li><a href="#list-group-custom-content">Custom content</a></li>
  </ul>
</li>
<li>
  <a href="#panels">Panels</a>
  <ul class="nav">
    <li><a href="#panels-basic">Basic example</a></li>
    <li><a href="#panels-heading">Panel with heading</a></li>
    <li><a href="#panels-alternatives">Contextual alternatives</a></li>
    <li><a href="#panels-tables">With tables</a>
    <li><a href="#panels-list-group">With list groups</a>
  </ul>
</li>
<li><a href="#wells">Wells</a></li>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/nav-css.html
<li>
  <a href="#overview">Overview</a>
  <ul class="nav">
    <li><a href="#overview-doctype">HTML5 doctype</a></li>
    <li><a href="#overview-mobile">Mobile first</a></li>
    <li><a href="#overview-responsive-images">Responsive images</a></li>
    <li><a href="#overview-type-links">Typography and links</a></li>
    <li><a href="#overview-normalize">Normalize</a></li>
    <li><a href="#overview-container">Containers</a></li>
  </ul>
</li>
<li>
  <a href="#grid">Grid system</a>
  <ul class="nav">
    <li><a href="#grid-media-queries">Media queries</a></li>
    <li><a href="#grid-options">Grid options</a></li>
    <li><a href="#grid-example-basic">Ex: Stacked-to-horizonal</a></li>
    <li><a href="#grid-example-mixed">Ex: Mobile and desktops</a></li>
    <li><a href="#grid-example-mixed-complete">Ex: Mobile, tablet, desktops</a></li>
    <li><a href="#grid-responsive-resets">Responsive column resets</a></li>
    <li><a href="#grid-offsetting">Offsetting columns</a></li>
    <li><a href="#grid-nesting">Nesting columns</a></li>
    <li><a href="#grid-column-ordering">Column ordering</a></li>
    <li><a href="#grid-less">LESS mixins and variables</a></li>
  </ul>
</li>
<li>
  <a href="#type">Typography</a>
  <ul class="nav">
    <li><a href="#type-headings">Headings</a></li>
    <li><a href="#type-body-copy">Body copy</a></li>
    <li><a href="#type-emphasis">Emphasis</a></li>
    <li><a href="#type-abbreviations">Abbreviations</a></li>
    <li><a href="#type-addresses">Addresses</a></li>
    <li><a href="#type-blockquotes">Blockquotes</a></li>
    <li><a href="#type-lists">Lists</a></li>
  </ul>
</li>
<li><a href="#code">Code</a></li>
<li>
  <a href="#tables">Tables</a>
  <ul class="nav">
    <li><a href="#tables-example">Basic example</a></li>
    <li><a href="#tables-striped">Striped rows</a></li>
    <li><a href="#tables-bordered">Bordered table</a></li>
    <li><a href="#tables-hover-rows">Hover rows</a></li>
    <li><a href="#tables-condensed">Condensed table</a></li>
    <li><a href="#tables-contextual-classes">Contextual classes</a></li>
    <li><a href="#tables-responsive">Responsive tables</a></li>
  </ul>
</li>
<li>
  <a href="#forms">Forms</a>
  <ul class="nav">
    <li><a href="#forms-example">Basic example</a></li>
    <li><a href="#forms-inline">Inline form</a></li>
    <li><a href="#forms-horizontal">Horizontal form</a></li>
    <li><a href="#forms-controls">Supported controls</a></li>
    <li><a href="#forms-controls-static">Static control</a></li>
    <li><a href="#forms-control-states">Control states</a></li>
    <li><a href="#forms-control-sizes">Control sizing</a></li>
    <li><a href="#forms-help-text">Help text</a></li>
  </ul>
</li>
<li>
  <a href="#buttons">Buttons</a>
  <ul class="nav">
    <li><a href="#buttons-options">Options</a></li>
    <li><a href="#buttons-sizes">Sizes</a></li>
    <li><a href="#buttons-disabled">Disabled state</a></li>
    <li><a href="#buttons-tags">Button tags</a></li>
  </ul>
</li>
<li>
  <a href="#images">Images</a>
</li>
<li>
  <a href="#helper-classes">Helper classes</a>
</li>
<li>
  <a href="#responsive-utilities">Responsive utilities</a>
  <ul class="nav">
    <li><a href="#responsive-utilities-classes">Available classes</a></li>
    <li><a href="#responsive-utilities-print">Print classes</a></li>
    <li><a href="#responsive-utilities-tests">Test cases</a></li>
  </ul>
</li>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/nav-customize.html
<li>
  <a href="#less">LESS components</a>
</li>
<li>
  <a href="#plugins">jQuery plugins</a>
</li>
<li>
  <a href="#less-variables">LESS variables</a>
  <ul class="nav">
    <li><a href="#variables-basics">Basics</a></li>
    <li><a href="#variables-buttons">Buttons</a></li>
    <li><a href="#variables-form-states">Form states</a></li>
    <li><a href="#variables-alerts">Alerts</a></li>
    <li><a href="#variables-navbar">Navbar</a></li>
    <li><a href="#variables-nav">Nav</a></li>
    <li><a href="#variables-tables">Tables</a></li>
    <li><a href="#variables-forms">Forms</a></li>
    <li><a href="#variables-dropdowns">Dropdowns</a></li>
    <li><a href="#variables-panels-wells">Panels and wells</a></li>
    <li><a href="#variables-accordion">Accordion</a></li>
    <li><a href="#variables-badges">Badges</a></li>
    <li><a href="#variables-breadcrumbs">Breadcrumbs</a></li>
    <li><a href="#variables-jumbotron">Jumbotron</a></li>
    <li><a href="#variables-modals">Modals</a></li>
    <li><a href="#variables-carousel">Carousel</a></li>
    <li><a href="#variables-list-group">List group</a></li>
    <li><a href="#variables-thumbnails">Thumbnails</a></li>
    <li><a href="#variables-progress">Progress bars</a></li>
    <li><a href="#variables-pagination">Pagination</a></li>
    <li><a href="#variables-pager">Pager</a></li>
    <li><a href="#variables-labels">Labels</a></li>
    <li><a href="#variables-tooltips-popovers">Tooltips and popovers</a></li>
    <li><a href="#variables-close">Close button</a></li>
    <li><a href="#variables-type">Type</a></li>
    <li><a href="#variables-other">Other</a></li>
  </ul>
</li>
<li>
  <a href="#download">Download</a>
</li>

kit/reminder/templates/reminder/bootstrap-3.0.0/_includes/nav-getting-started.html
<li>
  <a href="#download">Download Bootstrap</a>
  <ul class="nav">
    <li><a href="#download-compiled">Compiled CSS, JS, and fonts</a></li>
    <li><a href="#download-additional">Additional downloads</a></li>
    <li><a href="#download-cdn">Bootstrap CDN</a></li>
  </ul>
</li>
<li>
  <a href="#whats-included">What's included</a>
</li>
<li>
  <a href="#template">Basic template</a>
</li>
<li>
  <a href="#examples">Examples</a>
</li>
<li>
  <a href="#disable-responsive">Disabling responsiveness</a>
</li>
<li>
  <a href="#migration">Migrating from 2.x to 3.0</a>
  <ul class="nav">
    <li><a href="#migration-classes">Major class changes</a></li>
    <li><a href="#migration-new">What's new</a></li>
    <li><a href="#migration-dropped">What's removed</a></li>
    <li><a href="#migration-notes">Additional notes</a></li>
  </ul>
</li>
<li>
  <a href="#browsers">Browser support</a>
</li>
<li>
  <a href="#third-parties">Third party support</a>
</li>
<li>
  <a href="#accessibility">Accessibility</a>
</li>
<li>
  <a href="#license-faqs">License FAQs</a>
</li>
<li>
  <a href="#customizing">Customizing Bootstrap</a>
</li>

kit/reminder/templates/reminder/index.html
{% extends "base.html" %}

{% block title %}babble{% endblock %}

{% block content %}
<div class="container">
{% if user.is_authenticated %}

	<div class='page-header'>
		<h1><strong>hi.</strong>
		<br/>
		<small>
			<a href="{% url 'reminder:add_friend' %}"><button class="btn btn-babble">add friend</button></a>
			<a href="{% url 'reminder:add_event' %}"><button class="btn btn-babble">add event</button></a>
		</small>
		</h1>
	</div>

	
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#friendCollapse">
					friends:</a>
				</h2>
			</div>
			<div id="friendCollapse" class="panel-collapse collapse in">
				<div class="panel-body">
					{% if friend_list %}
					<table class="table table-hover">
						{% for friend in friend_list %}
						<tr><td>{{ friend.firstName }}</td></tr>
						{% endfor %}
					
					{% else %}
						<p>No friends available.</p>
					{% endif %}
					</table>
				</div>
			</div>
		</div>
	</div>

	<br/>
	
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#eventCollapse">
					events:</a>
				</h2>
			</div>
			<div id="eventCollapse" class="panel-collapse collapse in">
				<div class="panel-body">
					{% if event_list %}
					<table class="table table-hover">
						{% for event in event_list %}
						<tr><td>{{ event.name }}</td></tr>
						{% endfor %}
					
					{% else %}
						<p>No events available.</p>
					{% endif %}
					</table>
				</div>
			</div>
		</div>
	</div>
	
	


{% else %}
	<br/>

		<div class="jumbotron">
			
				<h1>babble</h1>
				<p>hi.</p>
				<p><a class="btn btn-primary btn-lg" href="/accounts/add">Sign up. </a></p>
			
		</div>
	<p>hi.</p>
	<p>Put explanation here. </p>
	
	
{% endif %}
</div>
{% endblock %}